# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 14:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huruma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=14)),
                ('plotno_1', models.CharField(max_length=20)),
                ('fr_source1', models.CharField(max_length=20)),
                ('number_of', models.IntegerField()),
                ('type_of_de', models.CharField(max_length=50)),
                ('plot_cover', models.IntegerField()),
                ('approved_p', models.CharField(max_length=50)),
                ('compliance', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32737)),
            ],
        ),
    ]
