# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 14:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roysa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=14)),
                ('layer', models.CharField(max_length=32)),
                ('level', models.FloatField()),
                ('elevation', models.FloatField()),
                ('plotno_1', models.CharField(max_length=20)),
                ('fr_source1', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=254)),
                ('type_of_de', models.CharField(max_length=50)),
                ('cracks', models.CharField(max_length=50)),
                ('plot_cover', models.IntegerField()),
                ('verticalit', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32737)),
            ],
        ),
    ]
