# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 15:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_roysa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viwandani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_d', models.CharField(max_length=254)),
                ('building_1', models.CharField(max_length=254)),
                ('building_2', models.IntegerField()),
                ('building_3', models.CharField(max_length=254)),
                ('building_4', models.CharField(max_length=254)),
                ('building_5', models.CharField(max_length=254)),
                ('building_6', models.IntegerField()),
                ('building_7', models.CharField(max_length=254)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('building_8', models.FloatField()),
                ('building_9', models.FloatField()),
                ('further_te', models.CharField(max_length=254)),
                ('dev_type', models.CharField(max_length=254)),
                ('dev_type_o', models.CharField(max_length=254)),
                ('water_mete', models.IntegerField()),
                ('defects_no', models.CharField(max_length=254)),
                ('meta_insta', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
