# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 16:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_viwandani'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hurumaproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('entity', models.CharField(max_length=14)),
                ('plotno_1', models.CharField(max_length=20)),
                ('fr_source1', models.CharField(max_length=20)),
                ('hact', models.FloatField()),
                ('out', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('acres', models.FloatField()),
                ('hectares', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('no_offloor', models.IntegerField()),
                ('type_dev', models.CharField(max_length=50)),
                ('cracks_wl', models.CharField(max_length=50)),
                ('verticalit', models.CharField(max_length=10)),
                ('compliance', models.CharField(max_length=50)),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Huruma',
        ),
    ]
